import {useEffect,useRef,useState} from "react";
import {invoke} from "@tauri-apps/api/core";
import {listen} from "@tauri-apps/api/event";
import {pickOutputDestination} from "../lib/tauri";
import {parseContentsPages} from "../app/localTools";
import {t} from "../lib/i18n";
interface Word {id:string;text:string;bbox:number[];export_status?:string;export_issues?:string[];source_members?:string[]}
interface Page {page:number;status:string;native_text?:string;words?:Word[];review_reasons?:string[];error?:unknown}
interface PendingSave {journal_id:string;journal_sha256:string;status:string;recoverable:boolean;output_pdf:string|null;reason:string|null}
interface Result {draft_published?:boolean;completion_record_state?:string;pending_saves?:PendingSave[];runtime_compatible?:boolean;runtime_binding_status?:string;session_storage?:string;session_id:string;revision:number|null;status:string;pages:Page[];source_sha256:string;output_pdf?:string;export_review?:{member_id:string;text:string;issues:string[]}[];saved?:{output_pdf:string}}
interface Props {documentId:string;pageCount:number;currentPage:number;previewReady:boolean;disabled:boolean;onPage:(page:number)=>void;onBusy:(busy:boolean)=>void;onOpen:(path:string)=>void}
export function LocalOcrPanel({documentId,pageCount,currentPage,previewReady,disabled,onPage,onBusy,onOpen}:Props){
 const [enabled,setEnabled]=useState(false),[ready,setReady]=useState(false),[blockers,setBlockers]=useState<string[]>([]),[pages,setPages]=useState("1"),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState(""),[text,setText]=useState(""),[sourceProof,setSourceProof]=useState<string|null>(null),[requested,setRequested]=useState<string|null>(null),[saved,setSaved]=useState<string|null>(null),[query,setQuery]=useState(""),[hits,setHits]=useState<{page:number;consumer:string;bbox:number[]|null}[]>([]),[partial,setPartial]=useState(false),[stage,setStage]=useState("");
 const session=useRef<string|null>(null),active=useRef(false),epoch=useRef(0),cancelled=useRef(false),operation=useRef<{token:string;epoch:number;sid:string|null;pending:boolean;sent:boolean}|null>(null);
 const words=(result?.pages??[]).flatMap(p=>(p.words??[]).map(w=>({...w,page:p.page}))),word=words.find(w=>w.id===selected);
 const proofKey=JSON.stringify([documentId,result?.session_id,result?.source_sha256,result?.revision,word?.page,word?.id,word?.source_members,word?.bbox,text]);
 const call=(action:string,extra:Record<string,unknown>={})=>invoke<unknown>("local_ocr_call",{request:{documentId,mode:"local",action,...extra}});
 useEffect(()=>{let stale=false;invoke<{enabled:boolean}>("local_ocr_capabilities").then(x=>{if(!stale)setEnabled(x.enabled);}).catch(()=>{});return()=>{stale=true;};},[]);
 useEffect(()=>{epoch.current++;let stale=false;setResult(null);setReady(false);setSaved(null);setSelected("");setText("");setHits([]);setPartial(false);setSourceProof(null);setRequested(null);session.current=null;operation.current=null;cancelled.current=false;if(enabled)call("readiness").then(x=>{if(stale)return;const r=x as {local_runtime_ready:boolean;blockers:{message:string}[]};setReady(r.local_runtime_ready);setBlockers(r.blockers.map(b=>b.message));}).catch(e=>{if(!stale)setError(String(e));});return()=>{stale=true;epoch.current++;};},[documentId,enabled]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{setSourceProof(null);setRequested(null);setPartial(false);},[proofKey]);
 useEffect(()=>{if(requested===proofKey&&previewReady&&currentPage===word?.page){setSourceProof(proofKey);setRequested(null);}if(!previewReady||currentPage!==word?.page)setSourceProof(null);},[requested,proofKey,previewReady,currentPage,word?.page]);
 useEffect(()=>{let stale=false;let stop:(()=>void)|undefined;listen<{documentId:string;event:{session_id?:string;client_operation_id?:string;stage?:string;event?:string}}>("mpdf://mvp-progress",({payload})=>{const op=operation.current;if(stale||payload.documentId!==documentId||!active.current||!op||op.epoch!==epoch.current||payload.event.client_operation_id!==op.token)return;if(payload.event.session_id){if(op.sid&&op.sid!==payload.event.session_id)return;op.sid=payload.event.session_id;session.current=op.sid;if(op.pending)void deliverCancel(op);}setStage(payload.event.stage??payload.event.event??"");}).then(s=>{if(stale)s();else stop=s;});return()=>{stale=true;stop?.();};},[documentId]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>()=>{onBusy(false);},[onBusy]);
 async function run(action:string,extra:Record<string,unknown>={}){
  if(active.current)return;active.current=true;const ticket=epoch.current;const op=action==="start"?{token:crypto.randomUUID().replace(/-/g,""),epoch:ticket,sid:null,pending:false,sent:false}:null;if(op)operation.current=op;setBusy(true);onBusy(true);setError(null);setSourceProof(null);setRequested(null);setStage(action);
  try{const response=await call(action,{...(action!=="start"?{sessionId:session.current}:{}),...(op?{clientOperationId:op.token}:{}),...extra});if(ticket!==epoch.current)return;
   if(action==="search")setHits((response as {hits:typeof hits}).hits.filter(h=>h.consumer==="PDF exact Unicode"));
   else{const r=response as Result;if(action==="resume"||action==="reload")cancelled.current=false;setResult(r);session.current=r.session_id;setSelected("");setText("");setPartial(false);setHits([]);if(r.saved)setSaved(r.saved.output_pdf);else if(action!=="reload")setSaved(null);}
  }catch(e){if(ticket===epoch.current)setError(typeof e==="object"&&e!==null&&"message" in e?String(e.message):String(e));}
  finally{if(operation.current===op)operation.current=null;active.current=false;setBusy(false);onBusy(false);}
 }
 async function start(){const range=parseContentsPages(pages,pageCount);if(range.error){setError(range.error);return;}cancelled.current=false;session.current=null;setSaved(null);setResult(null);await run("start",{pages:range.pages});}
 async function deliverCancel(op:NonNullable<typeof operation.current>){if(op.sent||!op.sid||operation.current!==op||op.epoch!==epoch.current)return;op.sent=true;try{await call("cancel",{sessionId:op.sid,clientOperationId:op.token});if(operation.current===op&&op.epoch===epoch.current)setStage("cancel_requested");}catch(e){if(operation.current===op&&op.epoch===epoch.current)setError(String(e));}}
 async function cancel(){const op=operation.current;if(!op||!active.current||op.epoch!==epoch.current)return;op.pending=true;cancelled.current=true;setSourceProof(null);setRequested(null);setPartial(false);await deliverCancel(op);}
 async function review(action:"accept"|"reject"|"change"){if(!word||!result||result.draft_published===false||result.runtime_compatible===false||sourceProof!==proofKey||!previewReady||currentPage!==word.page||cancelled.current)return;await run("review",{expectedRevision:result.revision,actions:[{page:word.page,member_id:word.id,action,text}]});}
 async function save(){if(!result||result.draft_published===false||result.runtime_compatible===false)return;const dest=await pickOutputDestination("museion-local-reviewed.pdf");if(dest)await run("save",{expectedRevision:result.revision,outputPath:dest,partialConfirmed:partial});}
 if(!enabled)return null;const unavailable=disabled||busy,readOnly=result?.runtime_compatible===false||result?.draft_published===false,sourceValid=sourceProof===proofKey&&previewReady&&currentPage===word?.page&&!cancelled.current;
 return <section className="local-ocr-panel" aria-label={t("本地文字识别")}>
  <h2>{t("本地文字识别")}</h2><p role="status">{t("机器草稿：质量验收未通过，保存后仍需核对。全程在本机处理。")}</p>
  <details><summary>{t("组件状态")}: {ready?t("可运行"):t("缺少组件")}</summary>{blockers.map((b,i)=><p key={i}>{b}</p>)}</details>
  <label htmlFor="local-ocr-pages">{t("识别 PDF 页码")}</label><input id="local-ocr-pages" value={pages} disabled={unavailable} onChange={e=>setPages(e.target.value)}/><button data-testid="local-ocr-current" disabled={unavailable} onClick={()=>setPages(String(currentPage))}>{t("选择当前页")}</button><button data-testid="local-ocr-resume" disabled={unavailable} onClick={()=>void run("resume")}>{t("继续上次本地草稿")}</button><button data-testid="local-ocr-start" disabled={unavailable||!ready} onClick={()=>void start()}>{t("开始识别")}</button>
  {busy&&<p role="status">{t("正在处理")}: {stage}<button data-testid="local-ocr-cancel" disabled={!operation.current} onClick={()=>void cancel()}>{t("取消")}</button></p>}
  {error&&<p role="alert" data-testid="local-ocr-error">{error}</p>}
  {result&&<div data-testid="local-ocr-result"><p>{result.status==="completion_unverified"||result.status==="processing_unverified"?t("处理完成情况待确认"):result.status} · {result.draft_published===false?t("部分结果（仅查看）"):t("修订 {0}",result.revision)}</p>{result.pages.map(p=><p key={p.page}>{t("第 {0} 页",p.page)}: {p.status}{p.error?String(p.error):""}{p.review_reasons?.join("; ")}</p>)}
   {result.draft_published===false&&<p role="alert" data-testid="local-ocr-incomplete">{t("完整草稿尚未生成。已保存的页面结果可查看；未完成页面不会自动重新处理，更正和保存暂不可用。")}</p>}
   {result.draft_published===false&&result.pages.filter(p=>p.native_text).map(p=><details key={p.page}><summary>{t("第 {0} 页",p.page)} · {t("已保存的原文文字")}</summary><p style={{whiteSpace:"pre-wrap"}}>{p.native_text}</p></details>)}
   {(result.completion_record_state==="missing"||result.completion_record_state==="unreadable")&&<p role="alert" data-testid="local-ocr-completion-unverified">{t("草稿已保留，但处理完成记录缺失或无法读取。请先核对结果；不会自动重跑。")}</p>}
   {result.session_storage==="persistent-private"&&<p>{t("草稿保存在本机应用数据中，请保留原 PDF；不会自动重新识别。")}</p>}
   {result.session_storage==="legacy-temporary"&&<p role="status">{t("这是旧临时草稿；临时目录可能被系统清理，尚未自动迁移。")}</p>}
   {result.runtime_compatible===false&&<p role="alert" data-testid="local-ocr-runtime-stale">{t("草稿的处理版本无法确认或已改变。可查看历史结果；更正、保存与恢复收据已停用。")}</p>}
   {(result.pending_saves??[]).map(p=><div key={p.journal_id} data-testid="local-ocr-pending-save"><p>{p.output_pdf}</p>{p.status==="recovered"?<p>{t("保存收据已恢复，PDF 内容未改动。")}</p>:<><p role="status">{p.recoverable?t("发现完整 PDF，但保存收据未完成。确认机器草稿后可补齐收据；不会改写 PDF。"):t("无法确认这次保存，请保留现有文件。可以另选新文件名保存。")}</p>{p.recoverable&&<button data-testid="local-ocr-recover-save" disabled={unavailable||readOnly||!partial} onClick={()=>void run("recover-save",{expectedRevision:result.revision,saveJournalId:p.journal_id,saveJournalSha256:p.journal_sha256})}>{t("确认现有文件并恢复收据")}</button>}</>}</div>)}
   {!!result.export_review?.length&&<p role="alert" data-testid="local-ocr-export-review">{t("部分文字无法写入 PDF，原字符串仍在复核记录中；{0} 项待审。",result.export_review.length)}</p>}
   <label htmlFor="local-ocr-member">{t("选择文字核对")}</label><select id="local-ocr-member" value={selected} disabled={unavailable} onChange={e=>{const w=words.find(w=>w.id===e.target.value);setSelected(e.target.value);setText(w?.text??"");}}><option value="">{t("选择文字")}</option>{words.map(w=><option key={w.id} value={w.id}>{t("第 {0} 页",w.page)} · {w.text} · {w.export_status??"DRAFT"}</option>)}</select>
   {word&&<><p>{word.export_issues?.join(", ")}</p><button data-testid="local-ocr-source" disabled={unavailable} onClick={()=>{setSourceProof(null);setRequested(proofKey);onPage(word.page);}}>{t("查看原图并核对")}</button><textarea aria-label={t("待审文字")} id="local-ocr-text" value={text} disabled={unavailable} onChange={e=>setText(e.target.value)}/><p>{t("更改文字或页面后，需要重新查看原图。复核记录不代表整份人工验收。")}</p><button data-testid="local-ocr-accept" disabled={unavailable||readOnly||!sourceValid} onClick={()=>void review("accept")}>{t("接受此词")}</button><button data-testid="local-ocr-reject" disabled={unavailable||readOnly||!sourceValid} onClick={()=>void review("reject")}>{t("拒绝此词")}</button><button data-testid="local-ocr-change" disabled={unavailable||readOnly||!sourceValid} onClick={()=>void review("change")}>{t("保存更正")}</button></>}
   <button data-testid="local-ocr-reload" disabled={unavailable} onClick={()=>void run("reload")}>{t("从磁盘重新载入")}</button><label><input data-testid="local-ocr-partial" type="checkbox" disabled={unavailable} checked={partial} onChange={e=>setPartial(e.target.checked)}/>{t("我知道这是机器草稿，未识别和待审部分会保留")}</label><button data-testid="local-ocr-save" disabled={unavailable||readOnly||!result.output_pdf||!partial} onClick={()=>void save()}>{t("另存为新 PDF…")}</button>
   {saved&&<><p data-testid="local-ocr-saved">{saved}</p><button disabled={unavailable} onClick={()=>onOpen(saved)}>{t("打开保存的 PDF")}</button></>}
   {result.output_pdf&&<><label htmlFor="local-ocr-query">{t("原样搜索 PDF")}</label><input id="local-ocr-query" disabled={unavailable} value={query} onChange={e=>setQuery(e.target.value)}/><button data-testid="local-ocr-search" disabled={unavailable||!query} onClick={()=>void run("search",{query,savedPdf:saved})}>{t("搜索")}</button><div data-testid="local-ocr-hits">{hits.map((h,i)=><button key={i} onClick={()=>onPage(h.page)}>{t("第 {0} 页",h.page)}</button>)}</div><p>{t("使用 PDF 原样文字查询；字符规范化诊断另行统计。")}</p></>}
  </div>}
 </section>;
}
