import {useEffect,useRef,useState} from "react";
import {invoke} from "@tauri-apps/api/core";
import {listen} from "@tauri-apps/api/event";
import {t} from "../lib/i18n";
import {pickOutputDestination} from "../lib/tauri";
import {parseContentsPages} from "../app/localTools";
import type {ContentsDraft,LocalEntry} from "../app/localTools";
import {ContentsEditor} from "./ContentsEditor";
type Mode="local"|"critical-edition"|"paid"|"paid-contents";
interface Word {id:string;text:string;review?:boolean;export_status?:string;export_issues?:string[];bbox:number[];source_members?:string[]}
interface ReaderAlternative {alternative_id:string;text:string;page:number;source_sha256:string;revision:number;identity_status:string;decision_status:string;review_actions:{revision:number;action:string}[];raw_member_id:string|null;stream:string;image_sha256:string|null;raw_record:unknown;read_only:boolean}
interface ReaderAlternatives {source_sha256:string;revision:number;read_only:boolean;rows:ReaderAlternative[];coverage:{page:number;raw_records:number;adopted_records:number;alternative_records:number;unavailable_streams:string[]}[]}
interface Region {id:string;original_text:string;member_ids:string[];page_number:number;locator:string;bbox:number[]|null}
interface Page {page?:number;page_number?:number;status:string;error?:unknown;reason?:string;words?:Word[];native_text?:string;review_reasons?:string[];export_coverage?:{total_words:number;exported_words:number;pending_words:number};observation?:{regions:Region[]};overlay?:{regions:{id:string;decision:string;text?:string}[]}}
interface Readiness {local_runtime_ready:boolean;quality_ready:boolean;ready:boolean;distribution_ready:boolean;external_development_runtime:boolean;blockers:{code:string;message:string}[]}
interface Result {reader_alternatives?:ReaderAlternatives;source_sha256?:string;diagnostic_only?:boolean;export_locked?:boolean;directory_blocker?:string;decision?:{decision:string;export_locked:boolean;alert?:string;risks?:{code:string;severity:string}[]};session_id:string;mode:Mode;revision:number;pages?:Page[];status:string;provenance:string;output_pdf?:string;export_review?:{member_id:string;text:string;issues:string[]}[];table?:{entries:LocalEntry[];revision:number;source_sha256:string;raw_model_sha256:string;page_count:number};completion?:{review_required:boolean;error_code?:string;error?:unknown;evidence?:{exported_entries?:number;original_entry_denominator?:number;remaining_entries?:unknown[]};page_results?:{reason:string}[]};error?:unknown;provider_errors?:{http_status:number;code:string;message:string;no_retry:boolean;unsettled_reserve_usd:number}[];saved?:{output_pdf?:string;artifacts?:{bookmarks_pdf?:string}}}
interface Props {documentId:string;pageCount:number;currentPage:number;previewReady:boolean;disabled:boolean;onPage:(page:number)=>void;onBusy:(busy:boolean)=>void;onOpen:(path:string)=>void}
export function MvpPanel({documentId,pageCount,currentPage,previewReady,disabled,onPage,onBusy,onOpen}:Props){
 const [enabled,setEnabled]=useState(false),[mode,setMode]=useState<Mode>("local"),[readiness,setReadiness]=useState<Readiness|null>(null),[result,setResult]=useState<Result|null>(null);
 const [pages,setPages]=useState("1"),[importPath,setImportPath]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[elapsed,setElapsed]=useState(0),[stage,setStage]=useState("");
 const [preflight,setPreflight]=useState<unknown>(null);
 const [alternativeId,setAlternativeId]=useState("");
 const [wordId,setWordId]=useState(""),[text,setText]=useState(""),[query,setQuery]=useState(""),[hits,setHits]=useState<{page:number;consumer:string}[]>([]),[savedPdf,setSavedPdf]=useState<string|null>(null);
 const [draft,setDraft]=useState<ContentsDraft|null>(null),[selectedIds,setSelectedIds]=useState<string[]>([]),[partialConfirmed,setPartialConfirmed]=useState(false),[sourceSeen,setSourceSeen]=useState<string|null>(null),[targetSeen,setTargetSeen]=useState<string|null>(null);
 const [entrySourceSeen,setEntrySourceSeen]=useState<string|null>(null),[requestedPreview,setRequestedPreview]=useState<{key:string;kind:"source"|"target";page:number}|null>(null);
 const words=(result?.pages??[]).flatMap(p=>(p.words??[]).map(w=>({...w,page:p.page??1,selectionKey:JSON.stringify(["word",p.page??1,w.id])}))),regions=(result?.pages??[]).flatMap(p=>(p.observation?.regions??[]).map(r=>({...r,selectionKey:JSON.stringify(["region",r.page_number,r.id])})));
 const word=words.find(w=>w.selectionKey===wordId),region=regions.find(r=>r.selectionKey===wordId);
 const alternatives=mode==="local"&&result?.mode==="local"?result.reader_alternatives:undefined;
 const alternative=alternatives?.rows.find(row=>row.alternative_id===alternativeId);
 const alternativeSourceValid=!!alternative&&alternative.read_only&&alternatives?.read_only&&alternative.source_sha256===result?.source_sha256&&alternatives.source_sha256===result?.source_sha256&&alternative.revision===result?.revision&&alternatives.revision===result?.revision&&Number.isInteger(alternative.page)&&alternative.page>=1&&alternative.page<=pageCount;
 function viewAlternativeSource(){setSourceSeen(null);setRequestedMember(null);if(alternativeSourceValid&&alternative)onPage(alternative.page);}
 const memberPage=word?.page??region?.page_number;
 const memberKey=JSON.stringify([documentId,mode,result?.session_id,result?.source_sha256,result?.revision,wordId,word?.source_members??region?.member_ids,word?.bbox??region?.bbox,memberPage,text]);
 const [requestedMember,setRequestedMember]=useState<string|null>(null);
 const memberSourceValid=sourceSeen===memberKey&&previewReady&&currentPage===memberPage;
 useEffect(()=>{setSourceSeen(null);setRequestedMember(null);},[memberKey]);
 useEffect(()=>{if(!previewReady||currentPage!==memberPage)setSourceSeen(null);if(requestedMember===memberKey&&previewReady&&currentPage===memberPage){setSourceSeen(memberKey);setRequestedMember(null);}},[requestedMember,memberKey,previewReady,currentPage,memberPage]);
 const selectedEntry=draft?.entries.find(e=>e.id===draft.selectedId);
 const entryKey=JSON.stringify([documentId,mode,result?.session_id,result?.revision,selectedEntry?.id,selectedEntry?.evidence_ids,selectedEntry?.title,selectedEntry?.parent,selectedEntry?.source_page,selectedEntry?.target_pdf_page]);
 const sourceValid=entrySourceSeen===entryKey,targetValid=targetSeen===entryKey;
 useEffect(()=>{setEntrySourceSeen(null);setTargetSeen(null);setRequestedPreview(null);setPartialConfirmed(false);},[entryKey]);
 useEffect(()=>{if(requestedPreview?.key===entryKey&&previewReady&&currentPage===requestedPreview.page){if(requestedPreview.kind==="source")setEntrySourceSeen(entryKey);else setTargetSeen(entryKey);setRequestedPreview(null);}},[requestedPreview,entryKey,previewReady,currentPage]);
 function requestEntryPreview(kind:"source"|"target",page:number){setPartialConfirmed(false);if(kind==="source")setEntrySourceSeen(null);else setTargetSeen(null);setRequestedPreview({key:entryKey,kind,page});onPage(page);}
 const session=useRef<string|null>(null),active=useRef(false),selected=useRef("");
 const call=(action:string,extra:Record<string,unknown>={})=>invoke<unknown>("mvp_call",{request:{documentId,mode,action,...extra}});
 useEffect(()=>{invoke<{enabled:boolean}>("mvp_capabilities").then(r=>setEnabled(r.enabled)).catch(()=>{});},[]);
 useEffect(()=>{if(!enabled)return;let stale=false;setReadiness(null);setResult(null);setAlternativeId("");setDraft(null);setSavedPdf(null);setWordId("");setPreflight(null);setHits([]);setQuery("");setText("");setError(null);setSelectedIds([]);setPartialConfirmed(false);setSourceSeen(null);setEntrySourceSeen(null);setTargetSeen(null);setRequestedPreview(null);session.current=null;call("readiness").then(r=>{if(!stale)setReadiness(r as Readiness);}).catch(e=>{if(!stale)setError(String(e));});return()=>{stale=true;};},[enabled,mode,documentId]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{let stale=false;let stop:(()=>void)|undefined;listen<{documentId:string;event:{event?:string;session_id?:string;stage?:string}}>("mpdf://mvp-progress",({payload})=>{if(payload.documentId!==documentId||!active.current)return;if(payload.event.session_id)session.current=payload.event.session_id;setStage(payload.event.stage??payload.event.event??"running");}).then(s=>{if(stale)s();else stop=s;});return()=>{stale=true;stop?.();};},[documentId]);
 useEffect(()=>{if(!busy)return;setElapsed(0);const start=Date.now(),timer=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),500);return()=>clearInterval(timer);},[busy]);
 useEffect(()=>{return()=>onBusy(false);},[onBusy]);
 function adopt(r:Result){setAlternativeId("");setPreflight(null);setHits([]);setQuery("");setSavedPdf(null);setPartialConfirmed(false);setDraft(null);setResult(r);session.current=r.session_id;if(r.saved)setSavedPdf(r.saved.output_pdf??r.saved.artifacts?.bookmarks_pdf??null);if(r.table){const entries=r.table.entries;setSelectedIds(entries.filter(e=>["ready","manually_confirmed"].includes(String(e.state))).map(e=>e.id));setDraft({entries,result:{documentId,sessionId:r.session_id,table:{...r.table,source_entries:entries,navigation_projection:[]},intake:{routes:[],prepare_seconds:0,selected_pages:[],mode:"image"}},projection:"source",selectedId:entries[0]?.id??null,reviewed:false,dirty:false,history:[]});}setWordId("");setSourceSeen(null);setTargetSeen(null);}
 async function run(action:string,extra:Record<string,unknown>={}){if(active.current)return;active.current=true;setBusy(true);onBusy(true);setError(null);setStage(action);try{const r=await call(action,{...(action!=="start"&&action!=="import"?{sessionId:session.current}:{}),...extra});if(action==="preflight")setPreflight(r);else if(action==="search")setHits((r as {hits:typeof hits}).hits);else adopt(r as Result);}catch(e){setError(typeof e==="object"&&e!==null&&"message" in e?String(e.message):String(e));}finally{active.current=false;setBusy(false);onBusy(false);}}
 async function review(action:"accept"|"reject"|"change"){
  if(!result||!wordId||mode==="paid"||!memberSourceValid)return;let actions:Record<string,unknown>[]=[];
  if(word)actions=[{page:word.page,member_id:word.id,action,text}];
  if(region)actions=[{region_id:region.id,member_ids:region.member_ids,action,text,source_evidence:`App source-page review ${region.page_number}; source=${documentId}`,reviewer:"App review action; identity unverified",human_approved:false}];
  await run("review",{expectedRevision:result.revision,actions});
 }
 function proof(page:number){return {status:"ai_source_checked",reviewer:"App source-bound review action; human identity unverified",evidence_ref:`App source/target preview ${documentId} page ${page+1}`,source_sha256:result?.table?.source_sha256,pdf_page:page,title_position_checked:true};}
 async function reviewEntry(action:"accept"|"reject"|"change"){
  if(!result||!draft||result.export_locked||result.diagnostic_only)return;const entry=draft.entries.find(e=>e.id===draft.selectedId);if(!entry||!sourceValid||(action!=="reject"&&!targetValid))return;
  const op:Record<string,unknown>={id:entry.id,member_ids:entry.evidence_ids,op:action};
  if(action==="change")op.fields={title:entry.title,parent:entry.parent,target_pdf_page:entry.target_pdf_page};
  if(action!=="reject"){op.source_review=proof(entry.source_page);op.target_review=proof(entry.target_pdf_page??-1);}
  await run("review",{expectedRevision:result.revision,actions:[op]});
 }
 async function save(){if(!result||mode==="paid")return;const output=await pickOutputDestination(`museion-${mode}-reviewed.pdf`);if(output)await run("save",{expectedRevision:result.revision,outputPath:output,selectedIds,partialConfirmed});}
 if(!enabled)return null;
 const unavailable=disabled||busy;const entries=result?.table?.entries??[],exported=result?.completion?.evidence?.exported_entries,remaining=result?.completion?.evidence?.remaining_entries?.length;
 return <section className="mvp-panel" aria-label={t("OCR 开发诊断")}>
  <h2>{t("OCR 开发诊断")}</h2><p className="attention">{t("机器草稿 · 四模式均未通过完整质量验收。发布默认关闭。")}</p>
  <label htmlFor="mvp-mode">{t("识别模式")}</label><select id="mvp-mode" value={mode} disabled={unavailable} onChange={e=>setMode(e.target.value as Mode)}><option value="local">{t("通用本地：Apple＋residual＋Tesseract")}</option><option value="critical-edition">{t("校勘本：Apple＋residual / CLLG")}</option><option value="paid">{t("付费 OCR：Mistral＋Luna")}</option><option value="paid-contents">{t("付费目录：Luna")}</option></select>
  <div data-testid="mvp-readiness">{readiness?<><p>{t("本机依赖：{0} · 质量：未验收 · 分发：未闭合",readiness.local_runtime_ready?t("可运行"):t("缺失"))}</p>{readiness.blockers.map((b,i)=><p className="field-hint" key={i}>{b.code}: {b.message}</p>)}{readiness.external_development_runtime&&<p>{t("此候选使用显式外部开发运行环境，尚未证明移机。")}</p>}</>:<p>{t("正在检查组件…")}</p>}</div>
  {mode==="paid"&&<p role="status" data-testid="mvp-paid-diagnostic-only">{t("选择性付费 OCR 仅供诊断：App 尚未接通版本与原图身份复核，接受、更正和保存已停用。")}</p>}
  {mode==="local"||mode==="critical-edition"?<><label htmlFor="mvp-pages">{t("OCR PDF 页码")}</label><input id="mvp-pages" value={pages} disabled={unavailable} onChange={e=>setPages(e.target.value)}/><button data-testid="mvp-start" disabled={unavailable||!readiness?.local_runtime_ready} onClick={()=>{const range=parseContentsPages(pages,pageCount);if(range.error)setError(range.error);else void run("start",{pages:range.pages});}}>{t("启动本地诊断")}</button></>:<p>{t("云发送已停用。这里只导入已有真实结果，不触发请求或重试。新发送须确认图像、目的地、模型、费用及请求身份。")}</p>}
  <label htmlFor="mvp-import">{t("已有结果 JSON 路径")}</label><input id="mvp-import" value={importPath} disabled={unavailable} onChange={e=>setImportPath(e.target.value)}/><button data-testid="mvp-import-button" disabled={unavailable||!importPath} onClick={()=>void run("import",{importPath})}>{t("导入已有结果")}</button>
  {busy&&<div role="status">{t("正在处理：{0} · {1} 秒",stage,elapsed)}<button data-testid="mvp-cancel" onClick={()=>{setSourceSeen(null);setRequestedMember(null);if(session.current)void call("cancel",{sessionId:session.current}).then(()=>setStage("cancel_requested")).catch(e=>setError(String(e)));}}>{t("取消诊断")}</button></div>}
  {error&&<p role="alert" data-testid="mvp-error">{error}</p>}
  {result&&<div data-testid="mvp-result">
   {(mode==="paid"||mode==="paid-contents")&&<><button data-testid="mvp-preflight" disabled={unavailable} onClick={()=>void run("preflight")}>{t("查看发送范围与停止原因（不发送）")}</button>{preflight!==null&&<pre data-testid="mvp-preflight-result">{JSON.stringify(preflight,null,2)}</pre>}</>}<p>{result.status} · {t("修订 {0}",result.revision)} · {result.provenance}</p>{mode==="paid-contents"&&(result.export_locked||result.decision?.decision==="abstain"||result.diagnostic_only)&&<p role="alert" data-testid="mvp-directory-lock">{t("目录导出已锁定：存在覆盖风险或缺少完整准入记录。历史结果仅供诊断。")}{result.decision?.decision} {result.decision?.alert} {result.directory_blocker}{result.decision?.risks?.map(r=>`${r.code}: ${r.severity}`).join("; ")}</p>}{!!result.error&&<p role="alert">{JSON.stringify(result.error)}</p>}{result.provider_errors?.map((e,i)=><p role="alert" data-testid="mvp-provider-error" key={i}>{e.http_status} / {e.code}: {e.message} · {t("禁止重试；未知费用预留保留。")}</p>)}{result.completion?.page_results?.map((p,i)=><p key={i}>{p.reason}</p>)}
   {result.export_review&&result.export_review.length>0&&<p role="alert" data-testid="mvp-export-review">{t("PDF 文字层部分覆盖：{0} 词待审；原字符串仍保留在文本和 JSON。",result.export_review.length)}</p>}
   {(result.pages??[]).map((p,i)=><p key={i}>{t("第 {0} 页",p.page??p.page_number??i+1)}: {p.status}{p.export_coverage&&` · ${p.export_coverage.exported_words}/${p.export_coverage.total_words} · pending ${p.export_coverage.pending_words}`}{p.review_reasons?.join("; ")}{p.reason}{p.error?JSON.stringify(p.error):""}</p>)}
   {(words.length>0||regions.length>0)&&<><label htmlFor="mvp-member">{t("位置绑定的待审文字")}</label><select id="mvp-member" value={wordId} disabled={unavailable} onChange={e=>{const id=e.target.value;setAlternativeId("");setWordId(id);selected.current=id;const w=words.find(w=>w.selectionKey===id),r=regions.find(r=>r.selectionKey===id);setText(w?.text??r?.original_text??"");setSourceSeen(null);}}><option value="">{t("选择词或段落")}</option>{words.map(w=><option key={w.selectionKey} value={w.selectionKey}>{w.page} · {w.text} · {w.export_status??"DRAFT"}</option>)}{regions.map(r=><option key={r.selectionKey} value={r.selectionKey}>{r.page_number} · {r.original_text.slice(0,65)} · {r.locator} · paragraph_coarse</option>)}</select>
    {wordId&&<><button data-testid="mvp-source" disabled={unavailable} onClick={()=>{setSourceSeen(null);setRequestedMember(memberKey);onPage(word?.page??region?.page_number??currentPage);}}>{t("查看原页")}</button><p>{word?.export_issues?.join(", ")}{region&&t("段落几何，非逐字位置。UNKNOWN 不可采用。")}</p><textarea id="mvp-text" value={text} disabled={unavailable} onChange={e=>setText(e.target.value)}/><div><button data-testid="mvp-accept" disabled={unavailable||!memberSourceValid||mode==="paid"||region?.locator==="UNKNOWN"} onClick={()=>void review("accept")}>{t("接受")}</button><button data-testid="mvp-reject" disabled={unavailable||!memberSourceValid||mode==="paid"} onClick={()=>void review("reject")}>{t("拒绝")}</button><button data-testid="mvp-change" disabled={unavailable||!memberSourceValid||mode==="paid"||region?.locator==="UNKNOWN"} onClick={()=>void review("change")}>{t("更正并保存修订")}</button></div></>}
   </>}
   {alternatives&&<div data-testid="mvp-reader-alternatives">
    <h3>{t("未采用的识别读法")}</h3><p>{t("这些是保留的原始读法，可能对应已经识别的文字。它们不代表漏词或正确答案，仅供对照原页。")}</p>
    <p data-testid="mvp-alternative-denominator">{t("保留 {0} 条读法，未采用 {1} 条。",alternatives.coverage.reduce((n,p)=>n+p.raw_records,0),alternatives.rows.length)}</p>
    {alternatives.coverage.some(p=>p.unavailable_streams.length>0)&&<p>{t("部分页面没有保留此类原始记录，不会自动重新识别。")}</p>}
    <label htmlFor="mvp-alternative">{t("选择未采用的读法")}</label><select id="mvp-alternative" value={alternativeId} disabled={unavailable} onChange={e=>{setAlternativeId(e.target.value);setWordId("");setText("");setSourceSeen(null);setRequestedMember(null);}}><option value="">{t("选择读法")}</option>{alternatives.rows.map(row=><option key={row.alternative_id} value={row.alternative_id}>{row.page} · {row.text}</option>)}</select>
    {alternative&&<div data-testid="mvp-alternative-detail" data-read-only="true"><pre>{alternative.text}</pre><p>{alternative.review_actions[alternative.review_actions.length-1]?.action==="reject"?t("已记录拒绝，原始读法仍保留。"):alternative.decision_status==="NOT_RECORDED"?t("没有记录采用决定，原始读法仍保留。"):t("未采用，保留原处理记录。")}</p>{alternative.identity_status!=="UNIQUE"&&<p>{t("记录身份存在歧义，仅供查看。")}</p>}<button data-testid="mvp-alternative-source" disabled={unavailable||!alternativeSourceValid} onClick={viewAlternativeSource}>{t("查看此读法所在原页")}</button><p>{t("查看原页不会接受这条读法；识别框尚未验证。")}</p><details><summary>{t("查看原始记录")}</summary><pre>{JSON.stringify(alternative,null,2)}</pre></details></div>}
   </div>}
   {draft&&<><p data-testid="mvp-denominator">{t("原目录 {0} 条；当前选择 {1} 条。未选条目保留待审，不隐式提升子节点。",entries.length,selectedIds.length)}{exported!==undefined&&t("已导出 {0} 条，余 {1} 条待审。",exported,remaining??0)}</p>
    <ContentsEditor draft={draft} pageCount={pageCount} currentPage={currentPage} disabled={unavailable} onChange={entries=>{setPartialConfirmed(false);setEntrySourceSeen(null);setTargetSeen(null);setRequestedPreview(null);setDraft(d=>d?{...d,entries,dirty:true}:d);}} onProjection={()=>{}} onSelect={id=>{setDraft(d=>d?{...d,selectedId:id}:d);setSourceSeen(null);setTargetSeen(null);}} onSource={e=>requestEntryPreview("source",e.source_page+1)} onTarget={page=>requestEntryPreview("target",page)} onReviewed={()=>{}} onUndo={()=>{}}/>
    <p>{t("没有可靠条目框时，展示完整原页，不生成虚假框。")}</p><button data-testid="mvp-entry-source" disabled={unavailable||!selectedEntry} onClick={()=>{if(selectedEntry){requestEntryPreview("source",selectedEntry.source_page+1);}}}>{t("查看目录原页")}</button><button data-testid="mvp-entry-target" disabled={unavailable||selectedEntry?.target_pdf_page===null} onClick={()=>{if(selectedEntry?.target_pdf_page!==null&&selectedEntry?.target_pdf_page!==undefined){requestEntryPreview("target",selectedEntry.target_pdf_page+1);}}}>{t("核对目标原页")}</button>
    <button data-testid="mvp-entry-accept" disabled={unavailable||result.export_locked||result.diagnostic_only||!sourceValid||!targetValid||!previewReady||currentPage!==((selectedEntry?.target_pdf_page??-1)+1)} onClick={()=>void reviewEntry("accept")}>{t("记录源与目标复核")}</button><button data-testid="mvp-entry-reject" disabled={unavailable||result.export_locked||result.diagnostic_only||!sourceValid} onClick={()=>void reviewEntry("reject")}>{t("拒绝")}</button><button disabled={unavailable||result.export_locked||result.diagnostic_only||!sourceValid||!targetValid||!previewReady||!draft.dirty||currentPage!==((selectedEntry?.target_pdf_page??-1)+1)} onClick={()=>void reviewEntry("change")}>{t("保存条目更正")}</button>
    <label><input type="checkbox" checked={!!selectedEntry&&selectedIds.includes(selectedEntry.id)} disabled={unavailable||!selectedEntry} onChange={e=>{setPartialConfirmed(false);if(selectedEntry)setSelectedIds(ids=>e.target.checked?[...new Set([...ids,selectedEntry.id])]:ids.filter(id=>id!==selectedEntry.id));}}/>{t("选择当前条目导出")}</label><label><input data-testid="mvp-partial-confirm" type="checkbox" checked={partialConfirmed} disabled={unavailable} onChange={e=>setPartialConfirmed(e.target.checked)}/>{t("明确保存所选部分；其余仍待审")}</label>
   </>}
   <p>{t("复核动作保存为带源身份的记录，不代签整份人工验收。")}</p><button data-testid="mvp-reload" disabled={unavailable} onClick={()=>void run("reload")}>{t("从磁盘重载")}</button><button data-testid="mvp-save" disabled={unavailable||mode==="paid"||result.export_locked||result.diagnostic_only||(!result.output_pdf&&!draft)||(!!draft&&(!partialConfirmed||!selectedIds.length))} onClick={()=>void save()}>{t("保存 OCR 新 PDF…")}</button>
   {savedPdf&&<><p data-testid="mvp-saved">{savedPdf}</p><button data-testid="mvp-open-result" disabled={unavailable} onClick={()=>onOpen(savedPdf)}>{t("打开结果")}</button></>}
   {result.output_pdf&&<><label htmlFor="mvp-search">{t("搜索派生 PDF")}</label><input id="mvp-search" value={query} disabled={unavailable} onChange={e=>setQuery(e.target.value)}/><button data-testid="mvp-search-button" disabled={unavailable||!query} onClick={()=>void run("search",{query,savedPdf})}>{t("搜索")}</button><div data-testid="mvp-hits">{hits.map((h,i)=><button key={i} onClick={()=>onPage(h.page)}>{h.consumer} · {t("第 {0} 页",h.page)}</button>)}</div></>}
  </div>}
 </section>;
}
