import {render,screen,waitFor,fireEvent} from "@testing-library/react";
import {describe,it,expect,vi,beforeEach} from "vitest";
import {MvpPanel} from "./MvpPanel";
import {setLocale} from "../lib/i18n";
const ipc=vi.hoisted(()=>vi.fn());
vi.mock("@tauri-apps/api/core",()=>({invoke:ipc}));
vi.mock("@tauri-apps/api/event",()=>({listen:vi.fn().mockResolvedValue(()=>{})}));
vi.mock("../lib/tauri",()=>({pickOutputDestination:vi.fn()}));
const props={documentId:"source",pageCount:12,currentPage:1,previewReady:true,disabled:false,onPage:vi.fn(),onBusy:vi.fn(),onOpen:vi.fn()};
beforeEach(()=>{ipc.mockReset();setLocale("zh");});
describe("explicit MVP development boundaries",()=>{
 it("keeps the default release entry hidden",async()=>{ipc.mockResolvedValue({enabled:false});render(<MvpPanel {...props}/>);await waitFor(()=>expect(ipc).toHaveBeenCalled());expect(screen.queryByText("OCR 开发诊断")).toBeNull();});
 it("does not offer a cloud start when paid mode is selected",async()=>{ipc.mockImplementation((command:string)=>Promise.resolve(command==="mvp_capabilities"?{enabled:true}:{local_runtime_ready:true,quality_ready:false,distribution_ready:false,ready:false,blockers:[]}));render(<MvpPanel {...props}/>);await screen.findByText("OCR 开发诊断");fireEvent.change(screen.getByLabelText("识别模式"),{target:{value:"paid"}});await screen.findByText(/云发送已停用/);expect(screen.queryByTestId("mvp-start")).toBeNull();expect(ipc.mock.calls.some(c=>c[1]?.request?.action==="start")).toBe(false);});
 it("shows partial Unicode coverage and requires source viewing before review",async()=>{ipc.mockImplementation((command:string,args?:{request:{action:string}})=>Promise.resolve(command==="mvp_capabilities"?{enabled:true}:args?.request.action==="readiness"?{local_runtime_ready:true,blockers:[]}:{session_id:"a".repeat(32),mode:"local",status:"review_required",provenance:"imported-existing-result",revision:0,export_review:[{member_id:"w",text:"x",issues:["UNSUPPORTED_GLYPH"]}],pages:[{page:1,status:"EXPORT_REVIEW",words:[{id:"w",text:"x",bbox:[1,2,3,4],export_status:"EXPORT_REVIEW"}],export_coverage:{total_words:1,exported_words:0,pending_words:1}}]}));render(<MvpPanel {...props}/>);await screen.findByText("OCR 开发诊断");fireEvent.change(screen.getByLabelText("已有结果 JSON 路径"),{target:{value:"/result.json"}});fireEvent.click(screen.getByTestId("mvp-import-button"));await screen.findByTestId("mvp-export-review");fireEvent.change(screen.getByLabelText("位置绑定的待审文字"),{target:{value:"w"}});expect(screen.getByTestId("mvp-accept")).toBeDisabled();fireEvent.click(screen.getByTestId("mvp-source"));expect(screen.getByTestId("mvp-accept")).toBeEnabled();});
});
const tocResult={session_id:"b".repeat(32),mode:"paid-contents",revision:2,status:"review_required",provenance:"existing",table:{revision:2,source_sha256:"source",raw_model_sha256:"raw",page_count:12,entries:[{id:"entry",title:"Title",parent:null,source_page:2,target_pdf_page:5,state:"ready",evidence_ids:["proof"],source_bbox:null}]}};
function tocIpc(command:string,args?:{request:{action:string}}){return Promise.resolve(command==="mvp_capabilities"?{enabled:true}:args?.request.action==="readiness"?{local_runtime_ready:true,blockers:[]}:args?.request.action==="preflight"?{provider:"old-C-manifest"}:tocResult);}
async function importToc(){await screen.findByText("OCR 开发诊断");fireEvent.change(screen.getByLabelText("识别模式"),{target:{value:"paid-contents"}});fireEvent.change(screen.getByLabelText("已有结果 JSON 路径"),{target:{value:"/toc.json"}});fireEvent.click(screen.getByTestId("mvp-import-button"));await screen.findByTestId("mvp-entry-source");}
it("requires a loaded source before a loaded target can authorize review",async()=>{
 ipc.mockImplementation(tocIpc);const view=render(<MvpPanel {...props} previewReady={false}/>);await importToc();fireEvent.click(screen.getByTestId("mvp-entry-source"));fireEvent.click(screen.getByTestId("mvp-entry-target"));view.rerender(<MvpPanel {...props} currentPage={6} previewReady={true}/>);await waitFor(()=>expect(screen.getByTestId("mvp-entry-accept")).toBeDisabled());expect(screen.getByTestId("mvp-entry-reject")).toBeDisabled();
 fireEvent.click(screen.getByTestId("mvp-entry-source"));view.rerender(<MvpPanel {...props} currentPage={3} previewReady={true}/>);await waitFor(()=>expect(screen.getByTestId("mvp-entry-reject")).toBeEnabled());fireEvent.click(screen.getByTestId("mvp-entry-target"));view.rerender(<MvpPanel {...props} currentPage={6} previewReady={true}/>);await waitFor(()=>expect(screen.getByTestId("mvp-entry-accept")).toBeEnabled());fireEvent.click(screen.getByTestId("mvp-partial-confirm"));fireEvent.click(screen.getByTestId("mvp-entry-source"));expect(screen.getByTestId("mvp-partial-confirm")).not.toBeChecked();view.rerender(<MvpPanel {...props} documentId="new-source"/>);await waitFor(()=>expect(screen.queryByTestId("mvp-entry-accept")).toBeNull());
});
it("clears a paid manifest across mode and imported result changes",async()=>{
 ipc.mockImplementation(tocIpc);render(<MvpPanel {...props}/>);await importToc();fireEvent.click(screen.getByTestId("mvp-preflight"));await screen.findByText(/old-C-manifest/);fireEvent.change(screen.getByLabelText("识别模式"),{target:{value:"paid"}});await waitFor(()=>expect(screen.queryByTestId("mvp-preflight-result")).toBeNull());fireEvent.click(screen.getByTestId("mvp-import-button"));await screen.findByTestId("mvp-result");expect(screen.queryByTestId("mvp-preflight-result")).toBeNull();
});

it("invalidates legacy word proof on text edits and leaving the loaded source page",async()=>{
 ipc.mockImplementation((command:string,args?:{request:{action:string}})=>Promise.resolve(command==="mvp_capabilities"?{enabled:true}:args?.request.action==="readiness"?{local_runtime_ready:true,blockers:[]}:{session_id:"a".repeat(32),mode:"local",status:"review_required",provenance:"existing",revision:0,source_sha256:"hash",pages:[{page:1,status:"OK",words:[{id:"w",text:"alpha",bbox:[1,2,3,4],source_members:["member"]}]}]}));
 const view=render(<MvpPanel {...props} previewReady={false}/>);await screen.findByText("OCR 开发诊断");fireEvent.change(screen.getByLabelText("已有结果 JSON 路径"),{target:{value:"/result.json"}});fireEvent.click(screen.getByTestId("mvp-import-button"));await screen.findByTestId("mvp-result");fireEvent.change(screen.getByLabelText("位置绑定的待审文字"),{target:{value:"w"}});fireEvent.click(screen.getByTestId("mvp-source"));expect(screen.getByTestId("mvp-accept")).toBeDisabled();view.rerender(<MvpPanel {...props}/>);await waitFor(()=>expect(screen.getByTestId("mvp-accept")).toBeEnabled());fireEvent.change(document.getElementById("mvp-text")!,{target:{value:"beta"}});expect(screen.getByTestId("mvp-accept")).toBeDisabled();fireEvent.change(document.getElementById("mvp-text")!,{target:{value:"alpha"}});expect(screen.getByTestId("mvp-accept")).toBeDisabled();fireEvent.click(screen.getByTestId("mvp-source"));await waitFor(()=>expect(screen.getByTestId("mvp-accept")).toBeEnabled());view.rerender(<MvpPanel {...props} currentPage={2}/>);expect(screen.getByTestId("mvp-accept")).toBeDisabled();view.rerender(<MvpPanel {...props} currentPage={1}/>);expect(screen.getByTestId("mvp-accept")).toBeDisabled();
});
it("keeps selective paid results explicitly diagnostic and cannot submit incompatible review/save",async()=>{
 ipc.mockImplementation((command:string,args?:{request:{action:string}})=>Promise.resolve(command==="mvp_capabilities"?{enabled:true}:args?.request.action==="readiness"?{local_runtime_ready:true,blockers:[]}:{session_id:"a".repeat(32),mode:"paid",status:"review_required",provenance:"selective-v3",revision:0,output_pdf:"/draft.pdf",pages:[{page_number:1,status:"OK",observation:{regions:[{id:"r",original_text:"alpha",member_ids:["m"],page_number:1,locator:"LOCATED",bbox:[1,2,3,4]}]}}]}));
 render(<MvpPanel {...props}/>);await screen.findByText("OCR 开发诊断");fireEvent.change(screen.getByLabelText("识别模式"),{target:{value:"paid"}});await screen.findByTestId("mvp-paid-diagnostic-only");fireEvent.change(screen.getByLabelText("已有结果 JSON 路径"),{target:{value:"/selective.json"}});fireEvent.click(screen.getByTestId("mvp-import-button"));await screen.findByTestId("mvp-result");fireEvent.change(screen.getByLabelText("位置绑定的待审文字"),{target:{value:"r"}});fireEvent.click(screen.getByTestId("mvp-source"));await waitFor(()=>expect(screen.getByTestId("mvp-accept")).toBeDisabled());expect(screen.getByTestId("mvp-reject")).toBeDisabled();expect(screen.getByTestId("mvp-change")).toBeDisabled();expect(screen.getByTestId("mvp-save")).toBeDisabled();expect(ipc.mock.calls.some(c=>["review","save"].includes(c[1]?.request.action))).toBe(false);
});
